
class PsValueHolder {
  PsValueHolder(
      {required this.loginUserId,
      required this.loginUserName,
      required this.locationId,
      required this.locactionName,
      required this.locationLat,
      required this.locationLng,
      required this.locationTownshipId,
      required this.locationTownshipName,
      required this.locationTownshipLat,
      required this.locationTownshipLng,
      required this.userIdToVerify,
      required this.userNameToVerify,
      required this.userEmailToVerify,
      required this.userPasswordToVerify,
      required this.deviceToken,
      required this.isSubLocation,
      required this.defaultCurrency,
      required this.defaultCurrencyId,
      required this.notiSetting,
      required this.isCustomCamera,
      required this.isToShowIntroSlider,
      required this.overAllTaxLabel,
      required this.overAllTaxValue,
      required this.shippingTaxLabel,
      required this.shopId,
      required this.messenger,
      required this.whatsApp,
      required this.phone,
      required this.shippingTaxValue,
      required this.appInfoVersionNo,
      required this.appInfoForceUpdate,
      required this.appInfoForceUpdateTitle,
      required this.appInfoForceUpdateMsg,
      required this.startDate,
      required this.endDate,
      required this.paypalEnabled,
      required this.stripeEnabled,
      required this.codEnabled,
      required this.bankEnabled,
      required this.publishKey,
      required this.shippingId,
      required this.standardShippingEnable,
      required this.zoneShippingEnable,
      required this.noShippingEnable,
      required this.detailOpenCount,
      required this.isPaidApp,
      required this.blockedFeatureDisabled,
      required this.title,
      required this.description, 
      required this.price, 
      required this.itemCurrencyId, 
      required this.locationCityId, 
      required this.propertyById,
      required this.postedId,
      required this.priceTypeId,
      required this.conditionOfItemId,
      required this.image,
      required this.video,
      required this.videoIcon,
      required this.discountRate,
      required this.highlightInfo,
      required this.priceUnit,
      required this.priceNote,
      required this.configuration,
      required this.area,
      required this.isNegotiable,
      required this.amenities,
      required this.floorNo,
      required this.address,
      required this.lat,
      required this.lng,
      required this.isPropertySubscribe,
      required this.maxImageCount,
      required this.googlePlayStoreUrl,
      required this.appleAppStoreUrl,
      required this.priceFormat,
      required this.dateFormat,
      required this.iosAppStoreId,
      required this.isUseThumbnailAsPlaceHolder,
      required this.isShowTokenId,
      required this.isShowSubcategory,
      required this.fbKey,
      required this.isShowAdmob,
      required this.defaultLoadingLimit,
      required this.categoryLoadingLimit,
      required this.postedByLoadingLimit,
      required this.agentLoadingLimit,
      required this.amenitiesLoadingLimit,
      required this.recentItemLoadingLimit,
      required this.populartItemLoadingLimit,
      required this.discountItemLoadingLimit,
      required this.featuredItemLoadingLimit,
      required this.blockSliderLoadingLimit,
      required this.followerItemLoadingLimit,
      required this.blockItemLoadingLimit,
      required this.showFacebookLogin,
      required this.showGoogleLogin,
      required this.showPhoneLogin,
      required this.isRazorSupportMultiCurrency,
      required this.defaultRazorCurrency,
      required this.itemDetailViewCountForAds,
      required this.isShowAdsInItemDetail,
      required this.isShowAdmobInsideList,
      required this.bluemarkSize,
      required this.mile,
      required this.videoDuration,
      required this.isUseGoogleMap,
      required this.profileImageSize,
      required this.uploadImageSize,
      required this.chatImageSize,
      required this.promoteFirstChoiceDay,
      required this.promoteSecondChoiceDay,
      required this.promoteThirdChoiceDay,
      required this.promoteFourthChoiceDay,
      required this.noFilterWithLocationOnMap,
      required this.isShowOwnerInfo,
      required this.isForceLogin,
      required this.isLanguageConfig,
      required this.defaultLanguageCode,
      required this.isUserAlradyChoose,
      required this.adType,
      required this.promoCellNo,
      required this.packageAndroidKeyList,
      required this.packageIOSKeyList,});
  String? locationId;
  String? locactionName;
  String? locationLat;
  String? locationLng;
  String locationTownshipId;
  String locationTownshipName;
  String locationTownshipLat;
  String locationTownshipLng;
  String? loginUserId;
  String? loginUserName;
  String? userIdToVerify;
  String? userNameToVerify;
  String? userEmailToVerify;
  String? userPasswordToVerify;
  String? deviceToken;
  String isSubLocation;
  String defaultCurrency;
  String defaultCurrencyId;
  bool? notiSetting;
  bool isCustomCamera;
  bool isToShowIntroSlider;
  String? overAllTaxLabel;
  String? overAllTaxValue;
  String? shippingTaxLabel;
  String? shopId;
  String? messenger;
  String? whatsApp;
  String? phone;
  String? shippingTaxValue;
  String? appInfoVersionNo;
  bool? appInfoForceUpdate;
  String? appInfoForceUpdateTitle;
  String? appInfoForceUpdateMsg;
  String? startDate;
  String? endDate;
  String? paypalEnabled;
  String? stripeEnabled;
  String? codEnabled;
  String? bankEnabled;
  String? publishKey;
  String? shippingId;
  String? standardShippingEnable;
  String? zoneShippingEnable;
  String? noShippingEnable;
  int? detailOpenCount;
  String? isPaidApp;
  String? blockedFeatureDisabled;
  String? title;
  String? description;
  String? price;
  String? itemCurrencyId;
  String? locationCityId;
  String? propertyById;
  String? postedId;
  String? priceTypeId;
  String? conditionOfItemId;
  String? image;
  String? video;
  String? videoIcon;
  String? discountRate;
  String? highlightInfo;
  String? priceUnit;
  String? priceNote;
  String? configuration;
  String? area;
  String? isNegotiable; 
  String? amenities; 
  String? floorNo;
  String? address;
  String? lat;
  String? lng; 
  String? isPropertySubscribe;
  int maxImageCount;
  String? googlePlayStoreUrl;
  String? appleAppStoreUrl;
  String? priceFormat;
  String? dateFormat;
  String? iosAppStoreId;
  bool? isUseThumbnailAsPlaceHolder;
  bool? isShowTokenId;
  bool? isShowSubcategory;
  String? fbKey;
  bool? isShowAdmob;
  int? defaultLoadingLimit;
  int? categoryLoadingLimit;
  int? postedByLoadingLimit;
  int? agentLoadingLimit;
  int? amenitiesLoadingLimit;
  int? recentItemLoadingLimit;
  int? populartItemLoadingLimit;
  int? discountItemLoadingLimit;
  int? featuredItemLoadingLimit;
  int? blockSliderLoadingLimit;
  int? followerItemLoadingLimit;
  int? blockItemLoadingLimit;
  bool? showFacebookLogin;
  bool? showGoogleLogin;
  bool? showPhoneLogin;
  bool? isRazorSupportMultiCurrency;
  String? defaultRazorCurrency;
  int? itemDetailViewCountForAds;
  bool? isShowAdsInItemDetail;
  bool? isShowAdmobInsideList;
  double? bluemarkSize;
  String? mile;
  String? videoDuration;
  bool? isUseGoogleMap;
  int? profileImageSize;
  int? uploadImageSize;
  int? chatImageSize;
  String? promoteFirstChoiceDay;
  String? promoteSecondChoiceDay;
  String? promoteThirdChoiceDay;
  String? promoteFourthChoiceDay;
  bool? noFilterWithLocationOnMap;
  bool? isShowOwnerInfo;
  bool? isForceLogin;
  bool? isLanguageConfig;
  String? defaultLanguageCode;
  bool? isUserAlradyChoose;
  String? adType;
  String? promoCellNo;
  String? packageAndroidKeyList;
  String? packageIOSKeyList;
}
